name: dl4nlp
channels:
  - defaults
  - conda-forge
dependencies:
  - python >=3.11
  - pip
  - pip:
    - numpy
    - pandas
    - torch
    - transformers
    - ipykernel
    - jupyter
    - accelerate
