name: dl4nlp
channels:
  - defaults
  - conda-forge
dependencies:
  - python >=3.11,<3.13
  - pip
  - pip:
    - accelerate==1.10.1
    - beautifulsoup4==4.13.5
    - huggingface-hub==0.34.4
    - ipykernel==6.30.1
    - ipython==9.5.0
    - ipywidgets==8.1.7
    - jupyter==1.1.1
    - jupyterlab==4.4.7
    - matplotlib==3.10.6
    - numpy==2.3.3
    - pandas==2.3.2
    - pillow==11.3.0
    - python-dotenv==1.1.1
    - requests==2.32.5
    - scikit-learn==1.7.2
    - scipy==1.16.2
    - sentencepiece==0.2.1
    - torch==2.8.0
    - tokenizers==0.22.0
    - tqdm==4.67.1
    - transformers==4.56.1
    - sacrebleu
    - autoflake
    - evaluate>=0.4.3
    - bitsandbytes>=0.45.3
    - trl>=0.21.0
    - peft>=0.14.0
    - wandb==0.22.0
    - flash-attn
