#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:30:00
#SBATCH --output=logs/install_environment_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1
module load CUDA/12.8.0

cd $HOME/dl4nlp

# conda env create -f environment.yml -n dl4nlp
conda env update --file environment.yml --prune

source activate dl4nlp
pip install flash-attn
conda deactivate
